- hosts: localhost
  become: yes 
  tasks:
  - name: install tomcat8
    apt: 
      name: tomcat8 
      state: present 
      update_cache: yes 
  - name: deploy application
    get_url:
     url: https://war-jar-vn.s3.amazonaws.com/gameoflife.war
     dest: /var/lib/tomcat8/webapps 
  - name: restart tomcat8 
    service: 
      name: tomcat8 
      state: restarted 
